## Uncomment the below code to Manually Test and  Automate the update on Telegram

# name: SitePulse Monitoring System

# on:
#   schedule:
#     - cron: "0 */6 * * *"            # To Check and Update every 6 hours
#   workflow_dispatch:                 # for Manual Test

# permissions:
#   contents: write

# jobs:
#   run:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.10"

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run sitepulse
#         env:
#           TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#           TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
#         run: |
#           python3 src/main.py

#       - name: Commit updated state (snapshots + suppression)
#         run: |
#           git config user.name "sitepulse-bot"
#           git config user.email "sitepulse-bot@users.noreply.github.com"

#           git add data/

#           git commit -m "chore: update snapshots and suppression state [auto]" || echo "No changes to commit"

#           git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
